# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapBiomasStyle
                                 A QGIS plugin
 Aplica automaticamente a simbologia do MapBiomas em camadas de uso do solo.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-05
        copyright            : (C) 2026 by -
        email                : ana@email.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapBiomasStyle class from file MapBiomasStyle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mapbiomas_style import MapBiomasStyle
    return MapBiomasStyle(iface)
